import { lighten } from "polished";

export const keen = {
  name: "Keen",

  COLOR_BRAND_PRIMARY: "#00b42b",
  COLOR_BRAND_SECONDARY: "#00b42b",

  COLOR_BACKGROUND_DEFAULT: "hsl(0, 0%, 100%)",
  COLOR_BACKGROUND_TWO: "#FDFDFE",
  COLOR_BACKGROUND_THREE: "hsl(0, 0%, 94%)",

  COLOR_CONTENT_DEFAULT: "hsla(0, 0%, 0%, 0.85)",
  COLOR_CONTENT_CONTRAST: "hsl(0, 0%, 0%)",
  COLOR_CONTENT_MUTED: "hsla(0, 0%, 0%, 0.6)",
  COLOR_CONTENT_NONESSENTIAL: "hsla(0, 0%, 0%, 0.3)",

  COLOR_INTENT_HIGHLIGHT: "#00b42b",
  COLOR_INTENT_SUCCESS: "#00b42b",
  COLOR_INTENT_DANGER: "#D83D22", // WCAG AA+
  COLOR_INTENT_WARNING: "#F7CD45", // WCAG AA+
  COLOR_INTENT_INFO: "#1E6DF6", // WCAG AA+

  COLOR_KEYLINE_DEFAULT: "hsla(0, 0%, 0%, 0.08)",
  COLOR_KEYLINE_SOLID: "hsl(0, 0%, 92%)",

  OPACITY_FULL: "1",
  OPACITY_LIGHT: "0.7",
  OPACITY_LIGHTER: "0.5",
  OPACITY_LIGHTEST: "0.15",

  // LAYOUT
  SPACING_BASE: 8,

  ZINDEX_ABYSS: "-9999",
  ZINDEX_FLOOR: "1",
  ZINDEX_DROPDOWN: "1010",
  ZINDEX_STICKY: "1020",
  ZINDEX_FIXED: "1030",
  ZINDEX_SCRIM: "1040",
  ZINDEX_MODAL: "1050",
  ZINDEX_POPOVER: "1060",
  ZINDEX_TOOLTIP: "1070",

  CORNER_RADIUS_SHARP: "2px", // spacingScale(0.5)
  CORNER_RADIUS_INPUT: "4px", // spacingScale(1)
  CORNER_RADIUS_CARD_SM: "4px",
  CORNER_RADIUS_CARD_DEFAULT: "6px",
  CORNER_RADIUS_CARD_LG: "8px",
  CORNER_RADIUS_MAX: "90000px",

  // TYPOGRAPHY
  FONT_STACK_DEFAULT: `Inter, -apple-system, BlinkMacSystemFont, "Segoe UI", "Roboto", "Oxygen", "Ubuntu", "Cantarell", "Fira Sans", "Droid Sans", "Helvetica Neue", sans-serif`,
  FONT_STACK_BRAND: `"Metropolis", "Helvetica Neue", Arial, sans-serif`,
  FONT_STACK_CODE: `"SFMono-Regular", Consolas, "Liberation Mono", Menlo, Courier, monospace`,

  FONT_SIZE_PAGE_TITLE: "40px",

  FONT_SIZE_HEADING_LG: "38px",
  FONT_SIZE_HEADING_DEFAULT: "36px",
  FONT_SIZE_HEADING_SM: "32px",

  FONT_SIZE_SUBHEADING_LG: "18px",
  FONT_SIZE_SUBHEADING_DEFAULT: "16px",
  FONT_SIZE_SUBHEADING_SM: "14px",

  FONT_SIZE_ITEM_TITLE_LG: "16px",
  FONT_SIZE_ITEM_TITLE_DEFAULT: "14px",
  FONT_SIZE_ITEM_TITLE_SM: "12px",

  FONT_SIZE_TEXT_XL: "18px",
  FONT_SIZE_TEXT_LG: "16px",
  FONT_SIZE_TEXT_DEFAULT: "14px",
  FONT_SIZE_TEXT_SM: "12px",
  FONT_SIZE_TEXT_XS: "10px",

  LINE_HEIGHT_LOOSE: 1.6,
  LINE_HEIGHT_DEFAULT: 1.4,
  LINE_HEIGHT_TIGHT: 1.2,

  FONT_WEIGHT_DEFAULT: 400,
  FONT_WEIGHT_MEDIUM: 500,
  FONT_WEIGHT_SEMIBOLD: 600,
  FONT_WEIGHT_BOLD: 700,

  LETTER_SPACING_DEFAULT: "normal"
};

const LIGHTENING_FACTOR = 0.05;

export const keenDark = {
  ...keen,

  name: "KeenDark",

  COLOR_BACKGROUND_DEFAULT: "#111",
  COLOR_BACKGROUND_TWO: "#181818",
  COLOR_BACKGROUND_THREE: "#242424",

  COLOR_CONTENT_DEFAULT: "hsla(0, 0%, 100%, 0.8)",
  COLOR_CONTENT_CONTRAST: "hsl(0, 0%, 100%)",
  COLOR_CONTENT_MUTED: "hsla(0, 0%, 100%, 0.6)",
  COLOR_CONTENT_NONESSENTIAL: "hsla(0, 0%, 100%, 0.5)",

  COLOR_INTENT_DANGER: lighten(LIGHTENING_FACTOR, keen.COLOR_INTENT_DANGER), // WCAG AA+
  COLOR_INTENT_WARNING: lighten(LIGHTENING_FACTOR, keen.COLOR_INTENT_WARNING), // WCAG AA+
  COLOR_INTENT_INFO: lighten(LIGHTENING_FACTOR, keen.COLOR_INTENT_INFO), // WCAG AA+

  COLOR_KEYLINE_DEFAULT: "hsla(0, 0%, 100%, 0.1)",
  COLOR_KEYLINE_SOLID: "hsla(0, 0%, 14%, 1)",

  LINE_HEIGHT_LOOSE: 1.7,
  LINE_HEIGHT_DEFAULT: 1.5,
  LINE_HEIGHT_TIGHT: 1.3,

  FONT_WEIGHT_DEFAULT: 500,
  FONT_WEIGHT_MEDIUM: 600,
  FONT_WEIGHT_SEMIBOLD: 700,
  FONT_WEIGHT_BOLD: 800,

  LETTER_SPACING_DEFAULT: "0.025ch"
};
