#!/bin/bash

set -eo pipefail

cmd_install () {
  local ci=""

  node_version=$(node --version | awk -Fv '{print $2}')

  # Compare the version with the minimum required version (17)
  if [[ "$(printf '%s\n' "17" "$node_version" | sort -V | head -n1)" != "17" ]]; then
      echo "Error: Node.js version $node_version is below the minimum required version (17)"
      exit 1
  fi
  
  echo "Required Node dependencies found."

  echo "Installing NPM dependencies..."
  if [[ $ci == "true" ]]; then
    npm ci
  else
    npm install
  fi
}

cmd_ci () {
  cmd_install "true"
}

cmd_help () {
  echo "This script will install NPM dependencies.

valid commands: ci, help

ci:
  Install NPM dependencies for CI environments.
help:
  Print this message and exit."
}

if [ $# -eq 0 ]; then
  cmd_install
else
  MODE="${1:-}"
  case "$MODE" in
    help|ci)
      shift
      "cmd_$MODE" "$@"
      ;;
    *)
      cmd_help
      ;;
  esac
fi
